### PR TITLE
Qt6

### PR DESCRIPTION
**Pull request by Olisehgenesis**

### CODE REVIEW

**Comment by Olisehgenesis** [comment]
Updates to Qt6

**Comment by Olisehgenesis** [comment]
If no comment in the next two weeks , I will compile and make an independent package

**Comment by Olisehgenesis** [comment]
Also haven't compiled, so installation of this branch currently do not work

**Comment by yjg30737** [comment]
Do as you wish :) This is for pyqt5 only.

**Comment by yjg30737** [comment]
You can make independent package out of pyqt6.

**Comment by Olisehgenesis** [comment]
Okay Thanks 🙏

**Pull request closed without merging**
